name: Publish API Guidance

on:
  push:
    branches:
      - main
    paths:
      - "DHSC.ANS.API.Consumer.Docs/output/**"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Copy output folder to temporary location
        run: |
          mkdir -p /tmp/api-guidance-output
          cp -R DHSC.ANS.API.Consumer.Docs/output/* /tmp/api-guidance-output/
      
      - name: Checkout or create api-guidance branch
        run: |
          if git rev-parse --verify api-guidance; then
            git checkout api-guidance
          else
            git checkout --orphan api-guidance
          fi

      - name: Remove existing files in api-guidance branch
        run: |
          git rm -rf . || true

      - name: Copy files from temporary location to branch
        run: |
          cp -R /tmp/api-guidance-output/* .
      
      - name: Stage and commit changes
        run: |
          git add .
          git commit -m "Update API Guidance" || echo "No changes to commit"
      
      - name: Push changes to api-guidance branch
        run: |
          git push --force --set-upstream origin api-guidance
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
